[CARE-2063] Image resized in published story different to editor option
prezly/content-renderer-react-js pull request #64
Opened 2023-07-19 11:47 UTC by fgyimah

https://github.com/prezly/content-renderer-react-js/assets/43710420/33f7ca58-5652-48b0-b066-eb48a39f47f5

2023-07-20 09:35 UTC, oleg-semyonov requested changes
Spotted a visual regression, can't approve yet.

2023-07-20 09:35 UTC, oleg-semyonov commented on .loki/reference/chrome_iphone7_Elements_Image_Left_Aligned.png
Looks like a regression. I was not sure that `px` width would work in this case, and this confirms my concern.

I believe that percent-based width is still the correct way to go, but it would be nice to get an opinion from others, especially @e1himself and @kudlajz

2023-07-20 10:13 UTC, e1himself commented on .loki/reference/chrome_iphone7_Elements_Image_Left_Aligned.png
The `width` property of the `ImageNode` is either percentage or pixels (the unit is part of the value; e.g. `width: "50%"` or `width: "120px"`).

See https://github.com/prezly/prezly/blob/cd8c9ea3f9dcada28718254df27d359377ce944f/lib/Prezly/App/Slate/Model/ImageNode.php#L19

So it should be used accordingly for rendering.

2023-07-20 10:31 UTC, fgyimah commented on .loki/reference/chrome_iphone7_Elements_Image_Left_Aligned.png
This was because for contained images, the `node.width`'s value was mostly coming in as 100%, that's why it always looked stretched and bigger compared to the editor, so I decided to go with the original size for contained images

2023-07-24 11:05 UTC, e1himself commented on .loki/reference/chrome_iphone7_Elements_Image_Left_Aligned.png
I believe I've fixed the problem with https://github.com/prezly/content-renderer-react-js/pull/64/commits/3f154ce64cfa34677ff18ac108f8c47984b8e59e

For explanation see https://linear.app/prezly/issue/CARE-2063/image-resized-in-published-story-different-to-editor-option#comment-ee5bbe02

2023-07-24 11:06 UTC, e1himself commented on src/elements/Image/Image.tsx
> +    return { width: node.width, maxWidth };
Adding `maxWidth` is what does the trick.

2023-07-24 11:07 UTC, e1himself commented on src/elements/Image/Image.tsx
> +    if (unit === '%' && parseFloat(node.width).toFixed(2) === Number(100).toFixed(2)) {
I also made sure that the renderer supports both `%` and `px` values in the `width` attribute.

2023-07-24 11:11 UTC, e1himself approved these changes

2023-07-24 11:42 UTC, merged